/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_example_games_tunnel_OurActivity_ScoreEntry */

#ifndef _Included_com_google_example_games_tunnel_OurActivity_ScoreEntry
#define _Included_com_google_example_games_tunnel_OurActivity_ScoreEntry
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
